### ISSUE TITLE
update to asp.net core 2.

### ISSUE THREAD

**Issue by touseefbsb** [dhananshan/PWA-Asp.NetCore#1]
asp.net core 2 has been officially released by Microsoft with some new templates for agular and react as well please check them and then kindly update this repo to asp.net core 2 as well
Thanks

**Comment by dhananshan** [comment]
@touseefbsb  Sure will do...

**Comment by touseefbsb** [comment]
yup thanks a lot :)

**Comment by dhananshan** [comment]
Updated to .net core 2.0
